name: todo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1
  loading_animation_widget: ^1.3.0
  page_transition: ^2.2.1
  flutter_expandable_fab: ^2.5.2

  # State Management
  flutter_riverpod: ^2.6.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  uuid: ^4.5.2

  # Date / Filters
  flutter_date_range_picker: ^0.2.1

  # Speech
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.1

  # Env config
  envied: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true